version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: journey-portfolio
    restart: unless-stopped
    networks:
      - traefik_network
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.club-connect.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.club-connect.entrypoints=web"
      - "traefik.http.services.club-connect.loadbalancer.server.port=80"

networks:
  traefik_network:
    external: true  
